from __future__ import annotations

from .faq_tax_matrix import CANONICAL_TAX_CODE_SOURCE_URL, TAX_CODE_FAQ_TOPICS

DOCUMENT_FIXTURES = [
    {
        "document_id": "7413ae69-672c-4c48-b3d5-8c04b09dfb43",
        "title": "საქართველოს საგადასახადო კოდექსი.",
        "document_type": "law",
        "source_url": CANONICAL_TAX_CODE_SOURCE_URL,
        "topics": list(dict.fromkeys(TAX_CODE_FAQ_TOPICS + ["property_tax"])),
        "subjects": ["individual", "legal_entity"],
        "goals": ["rate_lookup", "calculation_rule", "legal_basis"],
        "authority_rank": 1.0,
    },
    {
        "document_id": "funded-pension-law",
        "title": "დაგროვებითი პენსიის შესახებ საქართველოს კანონი",
        "document_type": "law",
        "source_url": "https://infohub.rs.ge/ka/workspace/document/64a515a7-f7be-4d1a-a9c1-aa9d008b6df8",
        "topics": ["funded_pension"],
        "subjects": ["individual"],
        "goals": ["contribution_rate", "legal_basis"],
        "authority_rank": 1.0,
    },
    {
        "document_id": "property-guidance-1432",
        "title": "ქონების გადასახადის მიზნებისთვის მეუღლეთა შემოსავლის გაანგარიშება N1432",
        "document_type": "guideline",
        "source_url": "https://infohub.rs.ge/ka/workspace/document/4e025ee8-641e-4cc2-a284-3ecb8ac5972e",
        "topics": ["tax", "property_tax"],
        "subjects": ["individual"],
        "goals": ["calculation_rule", "practical_guidance"],
        "authority_rank": 0.8,
    },
    {
        "document_id": "property-guidance-1433",
        "title": "მიწისა და მასზე განთავსებული შენობა-ნაგებობის დაბეგვრა ქონების გადასახადით N1433",
        "document_type": "guideline",
        "source_url": "https://infohub.rs.ge/ka/workspace/document/41e6c703-10ec-4d6e-aa01-d0e3f2e7afa5",
        "topics": ["tax", "property_tax"],
        "subjects": ["individual", "legal_entity"],
        "goals": ["calculation_rule", "practical_guidance"],
        "authority_rank": 0.78,
    },
    {
        "document_id": "ddcbd30f-a325-48ec-971a-922aa45a0b38",
        "title": "CUSTOMS CLEARANCE AND CUSTOMS CONTROL OF DUAL USE GOODS (GUAM countries) Handbook 2021-2023",
        "document_type": "guideline",
        "source_url": "https://infohub.rs.ge/ka/workspace/document/7fc0d360-9e3b-4ece-ab91-21c638cc77fc",
        "topics": ["customs"],
        "subjects": [],
        "goals": ["document_summary", "practical_guidance"],
        "authority_rank": 0.75,
    },
    {
        "document_id": "customs-dispute-19068-2-2023",
        "title": "გადაწყვეტილება №19068/2/2023",
        "document_type": "court_decision",
        "source_url": "https://infohub.rs.ge/ka/workspace/document/f8d0ca5b-2b73-4bc4-a09d-7e24d2121771",
        "topics": ["customs", "dispute"],
        "subjects": [],
        "goals": ["dispute_outcome"],
        "authority_rank": 0.82,
    },
    {
        "document_id": "dmanisi-property-tax-regulation-2025",
        "title": "ქალაქ დმანისის მუნიციპალიტეტის ქონების გადასახადის განაკვეთების შესახებ",
        "document_type": "regulation",
        "source_url": "https://infohub.rs.ge/ka/workspace/document/dmanisi-property-tax-regulation-2025",
        "topics": ["tax", "property_tax", "local_tax"],
        "subjects": ["individual", "legal_entity"],
        "goals": ["rate_lookup", "local_regulation"],
        "authority_rank": 0.88,
        "localities": ["dmanisi"],
        "is_current": True,
    },
    {
        "document_id": "tax-code-amendment-2026-vat",
        "title": "საქართველოს საგადასახადო კოდექსში ცვლილების შეტანის შესახებ 2026",
        "document_type": "law",
        "source_url": "https://infohub.rs.ge/ka/workspace/document/tax-code-amendment-2026-vat",
        "topics": ["tax", "vat", "amendment"],
        "subjects": ["individual", "legal_entity"],
        "goals": ["amendment_tracking", "legal_basis"],
        "authority_rank": 0.96,
        "is_current": True,
        "recency_bucket": "recent",
    },
]
